version: '3.8'

x-bancoestado-defaults: &bancoestado-defaults
  image: ms-bancoestado-integration:latest
  env_file:
    - ./.env
  networks:
    - ms_microservices-net

services:
  ms-bancoestado-integration:
    container_name: ms-bancoestado-integration
    build: .
    <<: *bancoestado-defaults
    volumes:
      - ./:/app
    expose:
      - "8000"
    restart: unless-stopped   
    command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

networks:
  ms_microservices-net:
    external: true
